theme = "evergreen"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = true
completion-replace = true

auto-format = true
auto-completion = true

[editor.cursor-shape]
insert = "bar"

normal = "block"

select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["file-type", "diagnostics", "selections", "position"]
separator = "│"
mode.normal = "󰶺  󰶻"
mode.insert = "󰶺  󰶻"
mode.select = "󰶺 󱉶 󰶻"

