theme = "evergreen"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = false
completion-replace = true
 
auto-format = true
auto-completion = true

[editor.cursor-shape]
insert = "bar"

normal = "block"

select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
[editor.whitespace.characters]
space = "."
tab = " "

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["file-type", "diagnostics", "selections", "position"]
separator = "│"
mode.normal = "[NOR]"
mode.insert = "[INS]"
mode.select = "[SEL]"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = "code_action"
A-q = ":bc"
C-q = ":bc!"
[keys.normal.t]
q = ":bco"
S-q = ":bco!"
