theme = "evergreen"

[editor]
line-number = "relative"
bufferline = "multiple"
mouse = false
completion-replace = true

auto-format = true
auto-completion = true

[editor.cursor-shape]
insert = "bar"

normal = "block"

select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
[editor.whitespace.characters]
tab = " "

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["file-type", "diagnostics", "selections", "position"]
separator = "│"
mode.normal = "󰶺  󰶻"
mode.insert = "󰶺  󰶻"
mode.select = "󰶺 󱉶 󰶻"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = "code_action"
